version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform:
- x86
- x64
- ARM
matrix:
  fast_finish: true
before_build:
  - nuget restore
install:
  - git submodule update --init --recursive
build:
  project: FridgeShoppingList.sln
  verbosity: detailed
